baseURL = "https://waeiski.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
theme = "lynx"
title = "Waeiski's link paradise"
copyright = "Copy, _right?_ :thinking_face:"
publishdir = "docs"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Tuomas Väisänen"
  headline = "Geospatial expert :earth_africa: Doctoral researcher :male_detective: at the University of Helsinki"
  image = "face.jpg"  # path relative to static directory

  links = [
    { link = { href = "https://researchportal.helsinki.fi/en/persons/tuomas-lauri-aleksanteri-v%C3%A4is%C3%A4nen", text = "Publications" } },
    { researchgate = "https://www.researchgate.net/profile/Tuomas-Vaeisaenen" },
    { mastodon = "https://vis.social/@waeiski" },
    { pixelfed = { href = "https://pixelfed.social/@waeiski", text = "PixelFed", icon = "pixelfed.svg" } },
    { twitter = "https://twitter.com/waeiski" },
    { instagram = "https://instagram.com/waeiski" },
    { github = "https://github.com/waeiski" },
    { linkedin = "https://linkedin.com/in/waeiski" }
    
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
