baseURL = "https://waeiski.github.io/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Tuomas Väisänen"
copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
_merge = "none"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Tuomas Väisänen"
  # email does still work but is deprecated.
  # use [params.contact.email] instead.
  #email = "john.doe@example.com"
  description = "Tuomas Väisänen's details"
  bio = "I am a geographer and a post-doctoral researcher in the Digital Geography Lab at the University of Helsinki. \n\nI am interested in GIScience, urban multilingualism, mobility, and segregation.\n \nHere are links to find me on other websites."
  avatar = "img/face2.png"
  error404 = "There is no such page."

  [params.contact]
    # the default fontawesome style in simple key-value pairs is "fab", i.e. brand icons
    instagram = "https://instagram.com/waeiski"
    twitter = "https://twitter.com/waeiski"
    
    # You may use (inline) tables for more versatility
    # This allows sorting and even more icons.
    # Just make sure not to mix key-value pairs, inline tables and tables,
    # although keeping keeping this order is ok.
    # See https://toml.io/en/v1.0.0 for details
    # 0 = { name = "ello", icon = "ello", style = "fab", link = "" } # empty links are possible
    [params.contact.1] # key names are sorted lexicographically
      name = "My publications" # may be omitted. defaults to key name
      icon = "scroll" # may be omitted. defaults to key name
      style = "fas" # may be omitted. default = "fas"
      link = "https://researchportal.helsinki.fi/en/persons/tuomas-lauri-aleksanteri-v%C3%A4is%C3%A4nen"
    [params.contact.2]
      style = "fab" # may be omitted. default = "fas"
      link = "https://vis.social/@waeiski"
      icon = "mastodon"
      name = "My Mastodon"
      # By default rel="me" is not set
      # For some services, it makes sense to set it though.
      # This is the case for Mastodon (and Github) if you link back from these services.
      # See
      # https://microformats.org/wiki/rel-me and
      # https://docs.joinmastodon.org/user/profile/#verification
      # for more information.
      # This defaults to false to cover the case of not having control over the linked site.
      rel-me = true
    [params.contact.3]
      style = "fas" # may be omitted. default = "fas"
      link = "https://pixelfed.social/@waeiski"
      icon = "camera-retro"
      name = "My PixelFed"
      # By default rel="me" is not set
      # For some services, it makes sense to set it though.
      # This is the case for Mastodon (and Github) if you link back from these services.
      # See
      # https://microformats.org/wiki/rel-me and
      # https://docs.joinmastodon.org/user/profile/#verification
      # for more information.
      # This defaults to false to cover the case of not having control over the linked site.
      rel-me = true
    [params.contact.4]
      name = "My GitHub"
      style = "fab" # may be omitted. default = "fas"
      link = "https://github.com/waeiski"
      icon = "github"
      # By default rel="me" is not set
      # For some services, it makes sense to set it though.
      # This is the case for Mastodon (and Github) if you link back from these services.
      # See
      # https://microformats.org/wiki/rel-me and
      # https://docs.joinmastodon.org/user/profile/#verification
      # for more information.
      # This defaults to false to cover the case of not having control over the linked site.
      rel-me = true
    [params.contact.5]
      name = "My ResearchGate"
      style = "fab" # may be omitted. default = "fas"
      link = "https://www.researchgate.net/profile/Tuomas-Vaeisaenen"
      icon = "researchgate"
      # By default rel="me" is not set
      # For some services, it makes sense to set it though.
      # This is the case for Mastodon (and Github) if you link back from these services.
      # See
      # https://microformats.org/wiki/rel-me and
      # https://docs.joinmastodon.org/user/profile/#verification
      # for more information.
      # This defaults to false to cover the case of not having control over the linked site.
      rel-me = true
    [params.contact.6]
      name = "My LinkedIn"
      style = "fab" # may be omitted. default = "fas"
      link = "https://linkedin.com/in/waeiski"
      icon = "linkedin"
      # By default rel="me" is not set
      # For some services, it makes sense to set it though.
      # This is the case for Mastodon (and Github) if you link back from these services.
      # See
      # https://microformats.org/wiki/rel-me and
      # https://docs.joinmastodon.org/user/profile/#verification
      # for more information.
      # This defaults to false to cover the case of not having control over the linked site.
      rel-me = true
    [params.contact.7]
      name = "My BlueSky"
      style = "fas" # may be omitted. default = "fas"
      link = "https://bsky.app/profile/waeiski.bsky.social"
      icon = "bluesky"
      # By default rel="me" is not set
      # For some services, it makes sense to set it though.
      # This is the case for Mastodon (and Github) if you link back from these services.
      # See
      # https://microformats.org/wiki/rel-me and
      # https://docs.joinmastodon.org/user/profile/#verification
      # for more information.
      # This defaults to false to cover the case of not having control over the linked site.
      rel-me = true
    [params.contact.email]
      name = "My email" # may be omitted. defaults to key name
      icon = "envelope" # may be omitted. defaults to key name
      style = "fas" # may be omitted. default = "fas"
      link = "mailto:tuomas.vaisanen@helsinki.fi"
      
